// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// order_sort
arma::uvec order_sort(const arma::vec& x);
RcppExport SEXP _NonparaTransport_order_sort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(order_sort(x));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau
double kendall_tau(const arma::uvec& order, const arma::vec& y);
RcppExport SEXP _NonparaTransport_kendall_tau(SEXP orderSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type order(orderSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau(order, y));
    return rcpp_result_gen;
END_RCPP
}
// bridge_inverse
double bridge_inverse(double tau);
RcppExport SEXP _NonparaTransport_bridge_inverse(SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(bridge_inverse(tau));
    return rcpp_result_gen;
END_RCPP
}
// make_positive_definite
arma::mat make_positive_definite(const arma::mat& mat, double nu);
RcppExport SEXP _NonparaTransport_make_positive_definite(SEXP matSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(make_positive_definite(mat, nu));
    return rcpp_result_gen;
END_RCPP
}
// latentcor_pointwise
arma::mat latentcor_pointwise(const arma::mat& data);
RcppExport SEXP _NonparaTransport_latentcor_pointwise(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(latentcor_pointwise(data));
    return rcpp_result_gen;
END_RCPP
}
// latentcor_matrix
arma::mat latentcor_matrix(const arma::mat& data, double nu);
RcppExport SEXP _NonparaTransport_latentcor_matrix(SEXP dataSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(latentcor_matrix(data, nu));
    return rcpp_result_gen;
END_RCPP
}
// general_precompute_proxy_parts
Rcpp::List general_precompute_proxy_parts(Rcpp::List data, int M, double nu);
RcppExport SEXP _NonparaTransport_general_precompute_proxy_parts(SEXP dataSEXP, SEXP MSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(general_precompute_proxy_parts(data, M, nu));
    return rcpp_result_gen;
END_RCPP
}
// bi_precompute_proxy_parts
Rcpp::List bi_precompute_proxy_parts(Rcpp::List data, int M, double nu);
RcppExport SEXP _NonparaTransport_bi_precompute_proxy_parts(SEXP dataSEXP, SEXP MSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(bi_precompute_proxy_parts(data, M, nu));
    return rcpp_result_gen;
END_RCPP
}
// general_pairwise_proxy_fast
arma::mat general_pairwise_proxy_fast(Rcpp::List summaries);
RcppExport SEXP _NonparaTransport_general_pairwise_proxy_fast(SEXP summariesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type summaries(summariesSEXP);
    rcpp_result_gen = Rcpp::wrap(general_pairwise_proxy_fast(summaries));
    return rcpp_result_gen;
END_RCPP
}
// bi_pairwise_proxy_fast
arma::mat bi_pairwise_proxy_fast(Rcpp::List summaries);
RcppExport SEXP _NonparaTransport_bi_pairwise_proxy_fast(SEXP summariesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type summaries(summariesSEXP);
    rcpp_result_gen = Rcpp::wrap(bi_pairwise_proxy_fast(summaries));
    return rcpp_result_gen;
END_RCPP
}
// general_pairwise_proxy_decompose
Rcpp::List general_pairwise_proxy_decompose(Rcpp::List summaries);
RcppExport SEXP _NonparaTransport_general_pairwise_proxy_decompose(SEXP summariesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type summaries(summariesSEXP);
    rcpp_result_gen = Rcpp::wrap(general_pairwise_proxy_decompose(summaries));
    return rcpp_result_gen;
END_RCPP
}
// bi_pairwise_proxy_decompose
Rcpp::List bi_pairwise_proxy_decompose(Rcpp::List summaries);
RcppExport SEXP _NonparaTransport_bi_pairwise_proxy_decompose(SEXP summariesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type summaries(summariesSEXP);
    rcpp_result_gen = Rcpp::wrap(bi_pairwise_proxy_decompose(summaries));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_distance
arma::mat pairwise_distance(List data, Function dist_func);
RcppExport SEXP _NonparaTransport_pairwise_distance(SEXP dataSEXP, SEXP dist_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Function >::type dist_func(dist_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_distance(data, dist_func));
    return rcpp_result_gen;
END_RCPP
}
// correlation_regression_cpp
Rcpp::List correlation_regression_cpp(Rcpp::List correlations, const arma::mat& X, const arma::mat& Z, int max_iter, double tolerance, double eigen_floor);
RcppExport SEXP _NonparaTransport_correlation_regression_cpp(SEXP correlationsSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP eigen_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type correlations(correlationsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type eigen_floor(eigen_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_regression_cpp(correlations, X, Z, max_iter, tolerance, eigen_floor));
    return rcpp_result_gen;
END_RCPP
}
// matched_component_losses_cpp
Rcpp::List matched_component_losses_cpp(Rcpp::List observed_quantiles, Rcpp::List predicted_quantiles, Rcpp::List observed_correlations, Rcpp::List predicted_correlations, double eigen_floor);
RcppExport SEXP _NonparaTransport_matched_component_losses_cpp(SEXP observed_quantilesSEXP, SEXP predicted_quantilesSEXP, SEXP observed_correlationsSEXP, SEXP predicted_correlationsSEXP, SEXP eigen_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_quantiles(observed_quantilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type predicted_quantiles(predicted_quantilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_correlations(observed_correlationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type predicted_correlations(predicted_correlationsSEXP);
    Rcpp::traits::input_parameter< double >::type eigen_floor(eigen_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(matched_component_losses_cpp(observed_quantiles, predicted_quantiles, observed_correlations, predicted_correlations, eigen_floor));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_summary_distance_cpp
Rcpp::List pairwise_summary_distance_cpp(Rcpp::List quantiles, Rcpp::List correlations, Rcpp::List cached_sqrts);
RcppExport SEXP _NonparaTransport_pairwise_summary_distance_cpp(SEXP quantilesSEXP, SEXP correlationsSEXP, SEXP cached_sqrtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type quantiles(quantilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type correlations(correlationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cached_sqrts(cached_sqrtsSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_summary_distance_cpp(quantiles, correlations, cached_sqrts));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau_a_cpp
double kendall_tau_a_cpp(const arma::vec& x, const arma::vec& y);
RcppExport SEXP _NonparaTransport_kendall_tau_a_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau_a_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distribution_summaries_cpp
Rcpp::List distribution_summaries_cpp(Rcpp::List data, int M, double pd_shrinkage, bool cache_sqrt);
RcppExport SEXP _NonparaTransport_distribution_summaries_cpp(SEXP dataSEXP, SEXP MSEXP, SEXP pd_shrinkageSEXP, SEXP cache_sqrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type pd_shrinkage(pd_shrinkageSEXP);
    Rcpp::traits::input_parameter< bool >::type cache_sqrt(cache_sqrtSEXP);
    rcpp_result_gen = Rcpp::wrap(distribution_summaries_cpp(data, M, pd_shrinkage, cache_sqrt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NonparaTransport_order_sort", (DL_FUNC) &_NonparaTransport_order_sort, 1},
    {"_NonparaTransport_kendall_tau", (DL_FUNC) &_NonparaTransport_kendall_tau, 2},
    {"_NonparaTransport_bridge_inverse", (DL_FUNC) &_NonparaTransport_bridge_inverse, 1},
    {"_NonparaTransport_make_positive_definite", (DL_FUNC) &_NonparaTransport_make_positive_definite, 2},
    {"_NonparaTransport_latentcor_pointwise", (DL_FUNC) &_NonparaTransport_latentcor_pointwise, 1},
    {"_NonparaTransport_latentcor_matrix", (DL_FUNC) &_NonparaTransport_latentcor_matrix, 2},
    {"_NonparaTransport_general_precompute_proxy_parts", (DL_FUNC) &_NonparaTransport_general_precompute_proxy_parts, 3},
    {"_NonparaTransport_bi_precompute_proxy_parts", (DL_FUNC) &_NonparaTransport_bi_precompute_proxy_parts, 3},
    {"_NonparaTransport_general_pairwise_proxy_fast", (DL_FUNC) &_NonparaTransport_general_pairwise_proxy_fast, 1},
    {"_NonparaTransport_bi_pairwise_proxy_fast", (DL_FUNC) &_NonparaTransport_bi_pairwise_proxy_fast, 1},
    {"_NonparaTransport_general_pairwise_proxy_decompose", (DL_FUNC) &_NonparaTransport_general_pairwise_proxy_decompose, 1},
    {"_NonparaTransport_bi_pairwise_proxy_decompose", (DL_FUNC) &_NonparaTransport_bi_pairwise_proxy_decompose, 1},
    {"_NonparaTransport_pairwise_distance", (DL_FUNC) &_NonparaTransport_pairwise_distance, 2},
    {"_NonparaTransport_correlation_regression_cpp", (DL_FUNC) &_NonparaTransport_correlation_regression_cpp, 6},
    {"_NonparaTransport_matched_component_losses_cpp", (DL_FUNC) &_NonparaTransport_matched_component_losses_cpp, 5},
    {"_NonparaTransport_pairwise_summary_distance_cpp", (DL_FUNC) &_NonparaTransport_pairwise_summary_distance_cpp, 3},
    {"_NonparaTransport_kendall_tau_a_cpp", (DL_FUNC) &_NonparaTransport_kendall_tau_a_cpp, 2},
    {"_NonparaTransport_distribution_summaries_cpp", (DL_FUNC) &_NonparaTransport_distribution_summaries_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_NonparaTransport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
