// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// correlation_regression_cpp
Rcpp::List correlation_regression_cpp(Rcpp::List correlations, const arma::mat& X, const arma::mat& Z, int max_iter, double tolerance, double eigen_floor);
RcppExport SEXP _NonparaTransport_correlation_regression_cpp(SEXP correlationsSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP eigen_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type correlations(correlationsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type eigen_floor(eigen_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_regression_cpp(correlations, X, Z, max_iter, tolerance, eigen_floor));
    return rcpp_result_gen;
END_RCPP
}
// matched_component_losses_cpp
Rcpp::List matched_component_losses_cpp(Rcpp::List observed_quantiles, Rcpp::List predicted_quantiles, Rcpp::List observed_correlations, Rcpp::List predicted_correlations, double eigen_floor);
RcppExport SEXP _NonparaTransport_matched_component_losses_cpp(SEXP observed_quantilesSEXP, SEXP predicted_quantilesSEXP, SEXP observed_correlationsSEXP, SEXP predicted_correlationsSEXP, SEXP eigen_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_quantiles(observed_quantilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type predicted_quantiles(predicted_quantilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_correlations(observed_correlationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type predicted_correlations(predicted_correlationsSEXP);
    Rcpp::traits::input_parameter< double >::type eigen_floor(eigen_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(matched_component_losses_cpp(observed_quantiles, predicted_quantiles, observed_correlations, predicted_correlations, eigen_floor));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_summary_distance_cpp
Rcpp::List pairwise_summary_distance_cpp(Rcpp::List quantiles, Rcpp::List correlations, Rcpp::List cached_sqrts);
RcppExport SEXP _NonparaTransport_pairwise_summary_distance_cpp(SEXP quantilesSEXP, SEXP correlationsSEXP, SEXP cached_sqrtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type quantiles(quantilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type correlations(correlationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cached_sqrts(cached_sqrtsSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_summary_distance_cpp(quantiles, correlations, cached_sqrts));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau_a_cpp
double kendall_tau_a_cpp(const arma::vec& x, const arma::vec& y);
RcppExport SEXP _NonparaTransport_kendall_tau_a_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau_a_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distribution_summaries_cpp
Rcpp::List distribution_summaries_cpp(Rcpp::List data, int M, double pd_shrinkage, bool cache_sqrt);
RcppExport SEXP _NonparaTransport_distribution_summaries_cpp(SEXP dataSEXP, SEXP MSEXP, SEXP pd_shrinkageSEXP, SEXP cache_sqrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type pd_shrinkage(pd_shrinkageSEXP);
    Rcpp::traits::input_parameter< bool >::type cache_sqrt(cache_sqrtSEXP);
    rcpp_result_gen = Rcpp::wrap(distribution_summaries_cpp(data, M, pd_shrinkage, cache_sqrt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NonparaTransport_correlation_regression_cpp", (DL_FUNC) &_NonparaTransport_correlation_regression_cpp, 6},
    {"_NonparaTransport_matched_component_losses_cpp", (DL_FUNC) &_NonparaTransport_matched_component_losses_cpp, 5},
    {"_NonparaTransport_pairwise_summary_distance_cpp", (DL_FUNC) &_NonparaTransport_pairwise_summary_distance_cpp, 3},
    {"_NonparaTransport_kendall_tau_a_cpp", (DL_FUNC) &_NonparaTransport_kendall_tau_a_cpp, 2},
    {"_NonparaTransport_distribution_summaries_cpp", (DL_FUNC) &_NonparaTransport_distribution_summaries_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_NonparaTransport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
