# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

order_sort <- function(x) {
    .Call(`_NonparaTransport_order_sort`, x)
}

kendall_tau <- function(order, y) {
    .Call(`_NonparaTransport_kendall_tau`, order, y)
}

bridge_inverse <- function(tau) {
    .Call(`_NonparaTransport_bridge_inverse`, tau)
}

make_positive_definite <- function(mat, nu = 0.001) {
    .Call(`_NonparaTransport_make_positive_definite`, mat, nu)
}

latentcor_pointwise <- function(data) {
    .Call(`_NonparaTransport_latentcor_pointwise`, data)
}

latentcor_matrix <- function(data, nu = 0) {
    .Call(`_NonparaTransport_latentcor_matrix`, data, nu)
}

general_precompute_proxy_parts <- function(data, M = 100L, nu = 0) {
    .Call(`_NonparaTransport_general_precompute_proxy_parts`, data, M, nu)
}

bi_precompute_proxy_parts <- function(data, M = 100L, nu = 0) {
    .Call(`_NonparaTransport_bi_precompute_proxy_parts`, data, M, nu)
}

general_pairwise_proxy_fast <- function(summaries) {
    .Call(`_NonparaTransport_general_pairwise_proxy_fast`, summaries)
}

bi_pairwise_proxy_fast <- function(summaries) {
    .Call(`_NonparaTransport_bi_pairwise_proxy_fast`, summaries)
}

general_pairwise_proxy_decompose <- function(summaries) {
    .Call(`_NonparaTransport_general_pairwise_proxy_decompose`, summaries)
}

bi_pairwise_proxy_decompose <- function(summaries) {
    .Call(`_NonparaTransport_bi_pairwise_proxy_decompose`, summaries)
}

pairwise_distance <- function(data, dist_func) {
    .Call(`_NonparaTransport_pairwise_distance`, data, dist_func)
}

correlation_regression_cpp <- function(correlations, X, Z, max_iter, tolerance, eigen_floor) {
    .Call(`_NonparaTransport_correlation_regression_cpp`, correlations, X, Z, max_iter, tolerance, eigen_floor)
}

matched_component_losses_cpp <- function(observed_quantiles, predicted_quantiles, observed_correlations, predicted_correlations, eigen_floor) {
    .Call(`_NonparaTransport_matched_component_losses_cpp`, observed_quantiles, predicted_quantiles, observed_correlations, predicted_correlations, eigen_floor)
}

pairwise_summary_distance_cpp <- function(quantiles, correlations, cached_sqrts) {
    .Call(`_NonparaTransport_pairwise_summary_distance_cpp`, quantiles, correlations, cached_sqrts)
}

kendall_tau_a_cpp <- function(x, y) {
    .Call(`_NonparaTransport_kendall_tau_a_cpp`, x, y)
}

distribution_summaries_cpp <- function(data, M, pd_shrinkage, cache_sqrt) {
    .Call(`_NonparaTransport_distribution_summaries_cpp`, data, M, pd_shrinkage, cache_sqrt)
}

