# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

correlation_regression_cpp <- function(correlations, X, Z, max_iter, tolerance, eigen_floor) {
    .Call(`_NonparaTransport_correlation_regression_cpp`, correlations, X, Z, max_iter, tolerance, eigen_floor)
}

matched_component_losses_cpp <- function(observed_quantiles, predicted_quantiles, observed_correlations, predicted_correlations, eigen_floor) {
    .Call(`_NonparaTransport_matched_component_losses_cpp`, observed_quantiles, predicted_quantiles, observed_correlations, predicted_correlations, eigen_floor)
}

pairwise_summary_distance_cpp <- function(quantiles, correlations, cached_sqrts) {
    .Call(`_NonparaTransport_pairwise_summary_distance_cpp`, quantiles, correlations, cached_sqrts)
}

kendall_tau_a_cpp <- function(x, y) {
    .Call(`_NonparaTransport_kendall_tau_a_cpp`, x, y)
}

distribution_summaries_cpp <- function(data, M, pd_shrinkage, cache_sqrt) {
    .Call(`_NonparaTransport_distribution_summaries_cpp`, data, M, pd_shrinkage, cache_sqrt)
}

